### ISSUE TITLE
Feature videos stretch on the homepage 

### ISSUE THREAD

**Issue by KevinNitroG** [longtoZ/score-gen-2#1]
Huhm will the object-contain work better than object-fill?

**Comment by longtoZ** [comment]
> Huhm will the object-contain work better than object-fill?

I dont even remember what i did lol!

**Comment by KevinNitroG** [comment]
https://github.com/longtoZ/score-gen-2/blob/main/client/src/components/home/Features.jsx

Hể

Ngủ đi bro

**Comment by longtoZ** [comment]
> https://github.com/longtoZ/score-gen-2/blob/main/client/src/components/home/Features.jsx
> 
> Hể
> 
> Ngủ đi bro

Dự án score bị bỏ quên r!

**Comment by KevinNitroG** [comment]
Ngủ đi bro
Giấc ngủ ngàn thu

Cùng cái project này
